### ISSUE TITLE
Antal avgångar

### ISSUE THREAD

**Issue by magdogg** [Gr3ytooth/sl-departure-card#1]
Hej, så glad att jag hittade detta kort!

En fråga bara: verkar som att det finns en tidsgränd för hur långt framåt i tid den tar med trafiken. Om det t.ex är glest mellan bussarna så syns ofta bara 3st trots min max antal på 8. Går det att förlänga tiden?

Tack igen/Magnus

**Comment by Gr3ytooth** [comment]
Hej
Kul att det kom till nytta för någon annan :)

I själva kortet så finns det ingen hantering för det, men i API-frågan mot Trafiklan så finns det något som heter forecast som anger hur många minuter i förväg man ska begära trafikinformation för. I den exempel-kod som jag skickade med så är det 120 minuter forecast. Tittade lite snabbt i Trafiklabs API-dokumentation (https://www.trafiklab.se/api/our-apis/sl/transport/#/default/Departures) och det verkar inte finnas någon begränsning i hur lång forecast man kan ha. Så prova att ändra 120 till 180 eller något sånt.

Exempel med 180 minuter
```
rest:
  - resource: https://transport.integration.sl.se/v1/sites/1080/departures?forecast=180
    method: GET
    sensor:
      - name: rest_sl_stockholm_c
        force_update: true
        value_template: "OK"
        json_attributes:
          - "departures"
          - "stop_deviations"
```
